import streamlit as st
import pandas as pd
from pypdf import PdfReader
from openai import OpenAI
import os
from dotenv import load_dotenv

load_dotenv()

# --- 1. UI 國際化語言包 (i18n Translations) ---
TRANSLATIONS = {
    "zh": {
        "page_title": "FinBrief · 財略摘要器",
        "title": "📊 FinBrief · 財略摘要器",
        "sidebar_settings": "⚙️ 系統與模型設定",
        "lang_select": "🌐 介面與報告語言 (Language)",
        "key_mode": "🔑 API Key 模式",
        "mode_server": "使用系統預設 Key (免輸入)",
        "mode_byok": "使用自備 API Key (BYOK)",
        "provider_select": "選擇 AI 服務商 (Provider)",
        "model_select": "選擇 / 輸入模型",
        "api_key_input": "輸入你的 API Key",
        "security_title": "🔒 數據隱私與技術說明",
        "tech_note_server": "💡 **免 Key 技術說明**：採用伺服器端金鑰安全託管 (Secrets Management)。連線全程經 TLS 加密代理處理，你的裝置與前端不會接觸到 API 金鑰。",
        "tech_note_byok": "💡 **BYOK 技術說明**：你輸入的金鑰僅存於 Session 記憶體中，絕不留存於伺服器數據庫，分頁關閉即自動銷毀。",
        "privacy_policy": """
        * **數據隱私**：上傳之財務報表數據僅用於當次 AI 摘要計算，伺服器不保存任何原始檔案。
        * **免責聲明**：本系統生成之分析僅供商業決策參考，不構成任何投資或會計審計建議。
        """,
        "upload_label": "上傳財務數據或報表 (PDF / Excel / CSV)",
        "template_label": "貼上你的標準分析模板或指令",
        "template_placeholder": "例如：請作為 C-Level 財務顧問分析：1. 核心營收與毛利趨勢 2. 現金流健康度 3. 三大潛在風險與建議。",
        "btn_generate": "🚀 生成財略報告",
        "err_no_key": "⚠️ 未偵測到有效的 API Key！請選擇「使用自備 API Key」並輸入 Key。",
        "err_no_file": "⚠️ 請先上傳財務檔案！",
        "err_no_template": "⚠️ 請輸入分析模板！",
        "report_header": "📈 FinBrief 財略分析報告",
        "btn_download": "📥 下載報告 (Markdown 格式)",
        "system_prompt": "你是一位精通香港會計準則 (HKFRS) 與國際財務報告準則 (IFRS) 的資深 C-Level 財務顧問與投資分析師。請用專業繁體中文輸出高品質財略報告。"
    },
    "en": {
        "page_title": "FinBrief · Financial Digest",
        "title": "📊 FinBrief · Financial Digest",
        "sidebar_settings": "⚙️ System & Model Settings",
        "lang_select": "🌐 Interface & Report Language",
        "key_mode": "🔑 API Key Mode",
        "mode_server": "Use System Default Key (No Key Needed)",
        "mode_byok": "Bring Your Own Key (BYOK)",
        "provider_select": "Select AI Provider",
        "model_select": "Select / Input Model",
        "api_key_input": "Enter your API Key",
        "security_title": "🔒 Data Privacy & Technology Notice",
        "tech_note_server": "💡 **No-Key Tech Note**: Powered by Server-side Secrets Management and TLS encrypted proxy. Your browser and client-side will never expose or store any API keys.",
        "tech_note_byok": "💡 **BYOK Tech Note**: Your API key is held exclusively in memory within the current session state and will be destroyed upon closing the browser tab.",
        "privacy_policy": """
        * **Data Privacy**: Uploaded financial documents are processed solely in memory for real-time analysis and are never stored on server disks.
        * **Disclaimer**: Reports generated by AI are for strategic reference only and do not constitute formal accounting, audit, or investment advice.
        """,
        "upload_label": "Upload Financial Data or Report (PDF / Excel / CSV)",
        "template_label": "Paste your Analysis Template or Prompt",
        "template_placeholder": "e.g., As a C-Level financial advisor, please analyze: 1. Core revenue & margin trends 2. Cash flow health 3. Top 3 strategic risks.",
        "btn_generate": "🚀 Generate Strategic Report",
        "err_no_key": "⚠️ No valid API Key detected! Please switch to BYOK mode and provide your API Key.",
        "err_no_file": "⚠️ Please upload a financial document first!",
        "err_no_template": "⚠️ Please input an analysis template!",
        "report_header": "📈 FinBrief Strategic Financial Report",
        "btn_download": "📥 Download Report (Markdown)",
        "system_prompt": "You are a senior C-Level financial advisor and investment analyst well-versed in HKFRS and IFRS. Please output a professional, high-level financial strategic report in English."
    }
}

# --- 2. 頁面初始化與語言選擇 ---
st.set_page_config(page_title="FinBrief", layout="wide")

with st.sidebar:
    lang_choice = st.radio("🌐 Language / 語言", options=["繁體中文", "English"], index=0)
    lang_code = "zh" if lang_choice == "繁體中文" else "en"
    t = TRANSLATIONS[lang_code]

    st.header(t["sidebar_settings"])
    
    # 選擇 API Key 模式
    key_mode = st.radio(
        t["key_mode"],
        options=[t["mode_server"], t["mode_byok"]]
    )
    
    # 判斷 API Key 來源
    if key_mode == t["mode_server"]:
        # 讀取伺服器端的環境變數 / Secrets
        active_api_key = os.getenv("OPENAI_API_KEY") or st.secrets.get("OPENAI_API_KEY", "")
        base_url = os.getenv("OPENAI_BASE_URL") or st.secrets.get("OPENAI_BASE_URL", None)
        selected_model = os.getenv("OPENAI_MODEL") or st.secrets.get("OPENAI_MODEL", "gpt-4o-mini")
        st.info(t["tech_note_server"])
    else:
        # BYOK 模式：用戶自行輸入
        active_api_key = st.text_input(t["api_key_input"], type="password")
        provider = st.selectbox(t["provider_select"], ["OpenAI", "DeepSeek / Custom Compatible API"])
        
        if provider == "OpenAI":
            selected_model = st.selectbox(t["model_select"], ["gpt-4o-mini", "gpt-4o"])
            base_url = None
        else:
            selected_model = st.text_input(t["model_select"], value="deepseek-chat")
            base_url = st.text_input("Base URL", value="https://api.deepseek.com")
            
        st.info(t["tech_note_byok"])

    st.markdown("---")
    st.markdown(f"### {t['security_title']}")
    st.caption(t["privacy_policy"])

# --- 3. 主畫面 UI ---
st.title(t["title"])

uploaded_file = st.file_uploader(t["upload_label"], type=['pdf', 'xlsx', 'csv'])
template = st.text_area(t["template_label"], height=150, placeholder=t["template_placeholder"])

def extract_text_from_pdf(file):
    pdf_reader = PdfReader(file)
    extracted_text = ""
    for page in pdf_reader.pages:
        text = page.extract_text()
        if text:
            extracted_text += text + "\n"
    return extracted_text

# --- 4. 報告生成邏輯 ---
if st.button(t["btn_generate"]):
    if not active_api_key:
        st.error(t["err_no_key"])
    elif not uploaded_file:
        st.warning(t["err_no_file"])
    elif not template.strip():
        st.warning(t["err_no_template"])
    else:
        file_type = uploaded_file.name.split('.')[-1].lower()
        extracted_content = ""

        with st.spinner("Processing file / 正在解析檔案..."):
            if file_type == 'pdf':
                extracted_content = extract_text_from_pdf(uploaded_file)
            elif file_type in ['xlsx', 'csv']:
                df = pd.read_excel(uploaded_file) if file_type == 'xlsx' else pd.read_csv(uploaded_file)
                extracted_content = df.to_string()

        with st.spinner("AI Analysis in progress / AI 正在進行財略分析..."):
            try:
                client = OpenAI(
                    api_key=active_api_key,
                    base_url=base_url if base_url else None
                )

                user_prompt = f"""
                【Analysis Requirements / 分析要求】:
                {template}

                【Financial Data / 財務數據】:
                {extracted_content[:100000]}
                """

                response = client.chat.completions.create(
                    model=selected_model,
                    messages=[
                        {"role": "system", "content": t["system_prompt"]},
                        {"role": "user", "content": user_prompt}
                    ],
                    temperature=0.2
                )

                report_text = response.choices[0].message.content

                st.markdown("---")
                st.markdown(f"## {t['report_header']}")
                st.markdown(report_text)
                
                st.download_button(
                    label=t["btn_download"],
                    data=report_text,
                    file_name=f"FinBrief_Report_{lang_code}.md",
                    mime="text/markdown"
                )

            except Exception as e:
                st.error(f"❌ AI Error: {str(e)}")
