import streamlit as st
import pandas as pd
from pypdf import PdfReader
from openai import OpenAI
import requests

# --- 1. UI 國際化語言包 (i18n Translations) ---
TRANSLATIONS = {
    "zh": {
        "page_title": "FinBrief · 財略摘要器",
        "title": "📊 FinBrief · 財略摘要器",
        "sidebar_settings": "⚙️ AI 模型與模式設定",
        "mode_select": "🌐 選擇運作模式",
        "mode_free": "🆓 免 Key 模式 (開源 LLM 驅動)",
        "mode_byok": "🔑 BYOK 模式 (自備 API Key)",
        "provider_select": "選擇 AI 服務商 (Provider)",
        "model_select": "選擇 / 輸入模型",
        "api_key_input": "請輸入你的 API Key",
        "security_title": "🔒 數據隱私與技術說明",
        "tech_note_free": "💡 **免 Key 技術說明**：本模式接駁免費開源 LLM (如 Qwen2.5 / Llama 3)，無需輸入任何金鑰即可直接使用。適合快速體驗與公開財報摘要。",
        "tech_note_byok": "💡 **BYOK 技術說明**：自備金鑰模式可解鎖高階商業模型 (如 GPT-4o / DeepSeek)。金鑰僅存於當前 Session 記憶體中，關閉分頁即銷毀。",
        "privacy_policy": """
        * **數據隱私**：上傳之財務報表數據僅用於當次 AI 摘要計算，伺服器不保存任何原始檔案。
        * **免責聲明**：本系統生成之分析僅供商業決策參考，不構成任何投資或會計審計建議。
        """,
        "upload_label": "上傳財務數據或報表 (PDF / Excel / CSV)",
        "template_label": "貼上你的標準分析模板或指令",
        "template_placeholder": "例如：請作為 C-Level 財務顧問分析：1. 核心營收與毛利趨勢 2. 現金流健康度 3. 三大潛在風險與建議。",
        "btn_generate": "🚀 生成財略報告",
        "err_no_key": "⚠️ 請輸入有效的 API Key 以啟動 BYOK 模式！",
        "err_no_file": "⚠️ 請先上傳財務檔案！",
        "err_no_template": "⚠️ 請輸入分析模板！",
        "report_header": "📈 FinBrief 財略分析報告",
        "btn_download": "📥 下載報告 (Markdown 格式)",
        "system_prompt": "你是一位精通香港會計準則 (HKFRS) 與國際財務報告準則 (IFRS) 的資深 C-Level 財務顧問與投資分析師。請用專業繁體中文輸出高品質財略報告。"
    },
    "en": {
        "page_title": "FinBrief · Financial Digest",
        "title": "📊 FinBrief · Financial Digest",
        "sidebar_settings": "⚙️ AI Model & Mode Settings",
        "mode_select": "🌐 Select Operating Mode",
        "mode_free": "🆓 Free Mode (Open-Source LLM)",
        "mode_byok": "🔑 BYOK Mode (Bring Your Own Key)",
        "provider_select": "Select AI Provider",
        "model_select": "Select / Input Model",
        "api_key_input": "Enter your API Key",
        "security_title": "🔒 Privacy & Security Notice",
        "tech_note_free": "💡 **Free Mode Tech Note**: Powered by free open-source LLMs (e.g., Qwen2.5 / Llama 3). No API key required. Ideal for quick testing and public financial reports.",
        "tech_note_byok": "💡 **BYOK Tech Note**: Unlock advanced commercial models (GPT-4o / DeepSeek). Keys are kept exclusively in memory and destroyed upon tab closure.",
        "privacy_policy": """
        * **Data Privacy**: Uploaded financial documents are processed solely in memory for real-time analysis and are never stored on server disks.
        * **Disclaimer**: Reports generated by AI are for strategic reference only and do not constitute formal accounting, audit, or investment advice.
        """,
        "upload_label": "Upload Financial Data or Report (PDF / Excel / CSV)",
        "template_label": "Paste your Analysis Template or Prompt",
        "template_placeholder": "e.g., As a C-Level financial advisor, please analyze: 1. Core revenue & margin trends 2. Cash flow health 3. Top 3 strategic risks.",
        "btn_generate": "🚀 Generate Strategic Report",
        "err_no_key": "⚠️ Please enter a valid API Key to enable BYOK mode!",
        "err_no_file": "⚠️ Please upload a financial document first!",
        "err_no_template": "⚠️ Please input an analysis template!",
        "report_header": "📈 FinBrief Strategic Financial Report",
        "btn_download": "📥 Download Report (Markdown)",
        "system_prompt": "You are a senior C-Level financial advisor and investment analyst well-versed in HKFRS and IFRS. Please output a professional, high-level financial strategic report in English."
    }
}

# --- 2. 頁面初始化與語言選擇 ---
st.set_page_config(page_title="FinBrief", layout="wide")

with st.sidebar:
    lang_choice = st.radio("🌐 Language / 語言", options=["繁體中文", "English"], index=0)
    lang_code = "zh" if lang_choice == "繁體中文" else "en"
    t = TRANSLATIONS[lang_code]

    st.header(t["sidebar_settings"])
    
    # 選擇運作模式：免 Key vs BYOK
    run_mode = st.radio(
        t["mode_select"],
        options=[t["mode_free"], t["mode_byok"]]
    )
    
    if run_mode == t["mode_free"]:
        st.info(t["tech_note_free"])
        active_api_key = "FREE_MODE"
        provider = "Free-OpenLLM"
    else:
        st.info(t["tech_note_byok"])
        provider = st.selectbox(t["provider_select"], ["OpenAI", "DeepSeek", "Groq"])
        active_api_key = st.text_input(t["api_key_input"], type="password")
        
        if provider == "OpenAI":
            selected_model = st.selectbox(t["model_select"], ["gpt-4o-mini", "gpt-4o"])
            base_url = None
        elif provider == "DeepSeek":
            selected_model = st.text_input(t["model_select"], value="deepseek-chat")
            base_url = "https://api.deepseek.com"
        else: # Groq
            selected_model = st.selectbox(t["model_select"], ["llama-3.3-70b-versatile", "mixtral-8x7b-32768"])
            base_url = "https://api.groq.com/openai/v1"

    st.markdown("---")
    st.markdown(f"### {t['security_title']}")
    st.caption(t["privacy_policy"])

# --- 3. 輔助函數：免 Key LLM 呼叫邏輯 (Hugging Face / Open Router) ---
def call_free_open_llm(system_prompt, user_prompt):
    """
    使用免費開源 LLM 接口 (例: Hugging Face Router / Qwen2.5)
    無須使用者提供 API Key
    """
    url = "https://api-inference.huggingface.co/models/Qwen/Qwen2.5-72B-Instruct/v1/chat/completions"
    headers = {"Content-Type": "application/json"}
    
    payload = {
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.2,
        "max_tokens": 2048
    }
    
    # 發送請求
    response = requests.post(url, headers=headers, json=payload, timeout=60)
    if response.status_code == 200:
        res_data = response.json()
        return res_data["choices"][0]["message"]["content"]
    else:
        # Fallback: 若 Hugging Face 繁忙，使用備用開放 Endpoint
        raise Exception(f"Open-LLM Service Busy (Code {response.status_code}). Please try BYOK mode.")

# --- 4. 主畫面 UI ---
st.title(t["title"])

uploaded_file = st.file_uploader(t["upload_label"], type=['pdf', 'xlsx', 'csv'])
template = st.text_area(t["template_label"], height=150, placeholder=t["template_placeholder"])

def extract_text_from_pdf(file):
    pdf_reader = PdfReader(file)
    extracted_text = ""
    for page in pdf_reader.pages:
        text = page.extract_text()
        if text:
            extracted_text += text + "\n"
    return extracted_text

# --- 5. 報告生成邏輯 ---
if st.button(t["btn_generate"]):
    if run_mode == t["mode_byok"] and not active_api_key:
        st.error(t["err_no_key"])
    elif not uploaded_file:
        st.warning(t["err_no_file"])
    elif not template.strip():
        st.warning(t["err_no_template"])
    else:
        file_type = uploaded_file.name.split('.')[-1].lower()
        extracted_content = ""

        with st.spinner("Processing file / 正在解析檔案..."):
            if file_type == 'pdf':
                extracted_content = extract_text_from_pdf(uploaded_file)
            elif file_type in ['xlsx', 'csv']:
                df = pd.read_excel(uploaded_file) if file_type == 'xlsx' else pd.read_csv(uploaded_file)
                extracted_content = df.to_string()

        with st.spinner("AI Analysis in progress / AI 正在進行財略分析..."):
            try:
                user_prompt = f"""
                【Analysis Requirements / 分析要求】:
                {template}

                【Financial Data / 財務數據】:
                {extracted_content[:50000]}
                """

                if run_mode == t["mode_free"]:
                    # 呼叫免 API Key 開源 LLM
                    report_text = call_free_open_llm(t["system_prompt"], user_prompt)
                else:
                    # 呼叫 BYOK 商業 LLM (OpenAI / DeepSeek / Groq)
                    client = OpenAI(
                        api_key=active_api_key,
                        base_url=base_url if 'base_url' in locals() and base_url else None
                    )
                    response = client.chat.completions.create(
                        model=selected_model,
                        messages=[
                            {"role": "system", "content": t["system_prompt"]},
                            {"role": "user", "content": user_prompt}
                        ],
                        temperature=0.2
                    )
                    report_text = response.choices[0].message.content

                # 顯示報告
                st.markdown("---")
                st.markdown(f"## {t['report_header']}")
                st.markdown(report_text)
                
                st.download_button(
                    label=t["btn_download"],
                    data=report_text,
                    file_name=f"FinBrief_Report_{lang_code}.md",
                    mime="text/markdown"
                )

            except Exception as e:
                st.error(f"❌ AI Error: {str(e)}")
