import streamlit as st
import pandas as pd
from pypdf import PdfReader
from openai import OpenAI
import requests
import urllib.parse
import os
import glob
from datetime import datetime

# --- 1. UI 國際化語言包與預設模板 (i18n & ISO Presets) ---
TRANSLATIONS = {
    "zh": {
        "page_title": "FinBrief · 財略摘要器",
        "title": "📊 FinBrief · 財略摘要器",
        "sidebar_settings": "⚙️ AI 模型與模式設定",
        "mode_select": "🌐 選擇運作模式",
        "mode_free": "🆓 免 Key 模式 (公開 LLM 驅動)",
        "mode_byok": "🔑 BYOK 模式 (自備 API Key)",
        "provider_select": "選擇 AI 服務商 (Provider)",
        "model_select": "選擇 / 輸入模型",
        "api_key_input": "請輸入你的 API Key",
        "security_title": "🔒 ISO 27001 & ISO 42001 合規與隱私說明",
        "tech_note_free": "💡 **免 Key 模式合規提醒**：採用公開免 Key 服務。根據 ISO 27001 資安規範，**請勿上傳未公開之商業機密或未發布財報**。",
        "tech_note_byok": "💡 **BYOK 模式合規優勢**：資料直接傳送至你指定的商業 API (如 OpenAI/DeepSeek)。金鑰僅存於 Session 記憶體，關閉分頁即銷毀。",
        "privacy_policy": """
        * **數據最小化 (ISO 27001)**：上傳之財務數據僅於記憶體中即時運算，伺服器不保存任何原始檔案。
        * **透明度與可追溯性 (ISO 42001)**：報告末端將自動附帶 AI Governance Audit Trail，紀錄 Prompt 框架與模型版本。
        * **免責聲明**：AI 生成之分析僅供商業決策參考，不構成任何正式審計、會計或法律建議。
        """,
        "consent_label": "我已閱讀並同意數據隱私與 ISO 合規說明",
        "upload_label": "上傳財務數據或報表 (PDF / Excel / CSV)",
        "preset_label": "💡 一鍵選擇標準分析模板：",
        "template_label": "分析模板與指令 (可自由微調)：",
        "presets": {
            "C-Level 核心財略摘要 (推薦)": "請作為 C-Level 財務顧問分析：\n1. 核心營收與毛利趨勢\n2. 現金流健康度與資本支出 (CAPEX)\n3. 三大潛在風險與戰略建議",
            "HKFRS 會計合規與資產負債審查": "請根據香港會計準則 (HKFRS) 視角拆解：\n1. 資產負債表健全度 (流動比率與債務結構)\n2. 損益表營運效率 (毛利率與純利率變化)\n3. 現金流量表經營品質分析",
            "併購與投資盡職調查 (M&A Due Diligence)": "請作為投資分析師進行簡要盡職調查：\n1. 企業核心盈利模式與護城河\n2. 潛在財務黑洞或隱性負債風險\n3. 未來 3 年成長性與估值觀察點"
        },
        "btn_generate": "🚀 生成財略報告",
        "err_no_consent": "⚠️ 請先勾選同意數據隱私與合規說明！",
        "err_no_key": "⚠️ 請輸入有效的 API Key 以啟動 BYOK 模式！",
        "err_no_file": "⚠️ 請先上傳財務檔案！",
        "err_no_template": "⚠️ 請選擇或輸入分析模板！",
        "report_header": "📈 FinBrief 財略分析報告",
        "btn_download": "📥 下載報告 (Markdown 格式)",
        "system_prompt": "你是一位精通香港會計準則 (HKFRS)、國際財務報告準則 (IFRS) 及企業戰略治理的資深 C-Level 財務顧問與投資分析師。請參考提供的多模組雙語權威知識庫，嚴格以專業繁體中文輸出高品質財略報告。"
    },
    "en": {
        "page_title": "FinBrief · Financial Digest",
        "title": "📊 FinBrief · Financial Digest",
        "sidebar_settings": "⚙️ AI Model & Mode Settings",
        "mode_select": "🌐 Select Operating Mode",
        "mode_free": "🆓 Free Mode (Public LLM)",
        "mode_byok": "🔑 BYOK Mode (Bring Your Own Key)",
        "provider_select": "Select AI Provider",
        "model_select": "Select / Input Model",
        "api_key_input": "Enter your API Key",
        "security_title": "🔒 ISO 27001 & ISO 42001 Compliance Notice",
        "tech_note_free": "💡 **Free Mode Compliance Warning**: Powered by public LLM proxies. Per ISO 27001 guidelines, **do NOT upload unreleased financial data or highly confidential trade secrets**.",
        "tech_note_byok": "💡 **BYOK Mode Compliance Advantage**: Direct API calls to commercial endpoints. Keys reside in session memory only and are destroyed on tab closure.",
        "privacy_policy": """
        * **Data Minimization (ISO 27001)**: Uploaded files are processed strictly in memory and never written to server disk.
        * **Transparency & Traceability (ISO 42001)**: Reports include an automated AI Governance Audit Trail capturing model and KB metadata.
        * **Disclaimer**: Output is generated by AI for strategic reference only and does not constitute formal accounting, audit, or legal advice.
        """,
        "consent_label": "I have read and agree to the Data Privacy & ISO Compliance Notice",
        "upload_label": "Upload Financial Data or Report (PDF / Excel / CSV)",
        "preset_label": "💡 Quick Select Standard Template:",
        "template_label": "Analysis Template & Instructions (Editable):",
        "presets": {
            "C-Level Strategic Digest (Recommended)": "As a C-Level financial advisor, please analyze:\n1. Core revenue & margin trends\n2. Cash flow health & CAPEX\n3. Top 3 strategic risks and actionable recommendations",
            "HKFRS Compliance & Balance Sheet Audit": "Deconstruct under HKFRS accounting view:\n1. Balance sheet robustness (Liquidity & debt structure)\n2. Income statement efficiency (Gross & net margin shifts)\n3. Operating cash flow quality",
            "M&A Due Diligence Quick Assessment": "As an investment analyst, perform a concise DD:\n1. Core business model & competitive moat\n2. Hidden liability risks or accounting red flags\n3. 3-Year growth potential & valuation drivers"
        },
        "btn_generate": "🚀 Generate Strategic Report",
        "err_no_consent": "⚠️ Please accept the Data Privacy & ISO Compliance Notice first!",
        "err_no_key": "⚠️ Please enter a valid API Key to enable BYOK mode!",
        "err_no_file": "⚠️ Please upload a financial document first!",
        "err_no_template": "⚠️ Please select or input an analysis template!",
        "report_header": "📈 FinBrief Strategic Financial Report",
        "btn_download": "📥 Download Report (Markdown)",
        "system_prompt": "You are a senior C-Level financial advisor and investment analyst well-versed in HKFRS, IFRS, and corporate strategic governance. Please refer to the provided multi-module bilingual Knowledge Base and output a professional, high-level financial strategic report strictly in English."
    }
}

# --- 2. 頁面初始化與語言選擇 ---
st.set_page_config(page_title="FinBrief", layout="wide")

with st.sidebar:
    lang_choice = st.radio("🌐 Language / 語言", options=["繁體中文", "English"], index=0)
    lang_code = "zh" if lang_choice == "繁體中文" else "en"
    t = TRANSLATIONS[lang_code]

    st.header(t["sidebar_settings"])
    
    run_mode = st.radio(
        t["mode_select"],
        options=[t["mode_free"], t["mode_byok"]]
    )
    
    if run_mode == t["mode_free"]:
        st.info(t["tech_note_free"])
        active_api_key = "FREE_MODE"
        selected_model = "public-open-llm"
    else:
        st.info(t["tech_note_byok"])
        provider = st.selectbox(t["provider_select"], ["OpenAI", "DeepSeek", "Groq"])
        active_api_key = st.text_input(t["api_key_input"], type="password")
        
        if provider == "OpenAI":
            selected_model = st.selectbox(t["model_select"], ["gpt-4o-mini", "gpt-4o"])
            base_url = None
        elif provider == "DeepSeek":
            selected_model = st.text_input(t["model_select"], value="deepseek-chat")
            base_url = "https://api.deepseek.com"
        else: # Groq
            selected_model = st.selectbox(t["model_select"], ["llama-3.3-70b-versatile", "mixtral-8x7b-32768"])
            base_url = "https://api.groq.com/openai/v1"

    st.markdown("---")
    st.markdown(f"### {t['security_title']}")
    st.caption(t["privacy_policy"])
    consent_given = st.checkbox(t["consent_label"], value=True)

# --- 3. 動態讀取模組化知識庫 (Knowledge Base Loader) ---
@st.cache_data
def load_knowledge_base():
    kb_dir = "knowledge_base"
    combined_kb_content = ""
    loaded_files = []
    
    if os.path.exists(kb_dir):
        md_files = glob.glob(os.path.join(kb_dir, "*.md"))
        for file_path in md_files:
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    filename = os.path.basename(file_path)
                    loaded_files.append(filename)
                    combined_kb_content += f"\n\n--- 知識模組: {filename} ---\n"
                    combined_kb_content += f.read()
            except Exception:
                pass
                
    if combined_kb_content:
        return f"\n\n【綜合權威知識庫 / Unified Domain Knowledge Base】\n{combined_kb_content}", loaded_files
    else:
        return "\n\n【Default Knowledge】: Analyze under standard HKFRS/IFRS framework.", ["Default System Prompt"]

# --- 4. 免 Key LLM 呼叫函數 ---
def call_free_open_llm(system_prompt, user_prompt):
    try:
        truncated_prompt = user_prompt[:8000]
        prompt_text = f"System: {system_prompt}\nUser: {truncated_prompt}"
        encoded_prompt = urllib.parse.quote(prompt_text)
        
        url = f"https://text.pollinations.ai/{encoded_prompt}?model=openai"
        response = requests.get(url, timeout=45)
        
        if response.status_code == 200 and len(response.text.strip()) > 0:
            return response.text
    except Exception:
        pass 

    try:
        url_b = "https://text.pollinations.ai/"
        payload_b = {
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt[:6000]}
            ],
            "model": "qwen",
            "code": "beartoken"
        }
        res_b = requests.post(url_b, json=payload_b, timeout=45)
        if res_b.status_code == 200 and len(res_b.text.strip()) > 0:
            return res_b.text
    except Exception:
        pass

    raise Exception("免費 LLM Endpoint 目前流量較高 (402/429)。建議稍後再試，或切換至「🔑 BYOK 模式」輸入 API Key 獲得商業級穩定體驗。")

# --- 5. 主畫面 UI 與一鍵模板選單 ---
st.title(t["title"])

uploaded_file = st.file_uploader(t["upload_label"], type=['pdf', 'xlsx', 'csv'])

st.write(t["preset_label"])
preset_options = list(t["presets"].keys())
selected_preset = st.selectbox("選擇預設範例 / Select Template", options=preset_options, index=0)

default_template_text = t["presets"][selected_preset]
template = st.text_area(t["template_label"], value=default_template_text, height=150)

def extract_text_from_pdf(file):
    pdf_reader = PdfReader(file)
    extracted_text = ""
    max_pages = min(len(pdf_reader.pages), 15)
    for i in range(max_pages):
        text = pdf_reader.pages[i].extract_text()
        if text:
            extracted_text += text + "\n"
    return extracted_text

# --- 6. 報告生成與 ISO 可追溯性元數據附加 ---
if st.button(t["btn_generate"]):
    if not consent_given:
        st.error(t["err_no_consent"])
    elif run_mode == t["mode_byok"] and not active_api_key:
        st.error(t["err_no_key"])
    elif not uploaded_file:
        st.warning(t["err_no_file"])
    elif not template.strip():
        st.warning(t["err_no_template"])
    else:
        file_type = uploaded_file.name.split('.')[-1].lower()
        extracted_content = ""

        with st.spinner("Processing file / 正在解析檔案關鍵內容..."):
            if file_type == 'pdf':
                extracted_content = extract_text_from_pdf(uploaded_file)
            elif file_type in ['xlsx', 'csv']:
                df = pd.read_excel(uploaded_file) if file_type == 'xlsx' else pd.read_csv(uploaded_file)
                extracted_content = df.to_string()

        with st.spinner("AI Analysis in progress / AI 正在載入 ISO 合規知識庫並進行分析..."):
            try:
                kb_text, kb_files = load_knowledge_base()
                full_system_prompt = t["system_prompt"] + kb_text

                user_prompt = f"""
                【Analysis Requirements / 分析要求】:
                {template}

                【Financial Data / 財務數據】:
                {extracted_content}
                """

                if run_mode == t["mode_free"]:
                    raw_report = call_free_open_llm(full_system_prompt, user_prompt)
                else:
                    client = OpenAI(
                        api_key=active_api_key,
                        base_url=base_url if 'base_url' in locals() and base_url else None
                    )
                    response = client.chat.completions.create(
                        model=selected_model,
                        messages=[
                            {"role": "system", "content": full_system_prompt},
                            {"role": "user", "content": user_prompt[:40000]}
                        ],
                        temperature=0.2
                    )
                    raw_report = response.choices[0].message.content

                # --- ISO 42001 可追溯性紀錄區塊 (Audit Trail Block) ---
                timestamp_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
                audit_trail = f"""

---
### 🛡️ AI Governance & ISO 42001 Audit Trail
* **Timestamp**: `{timestamp_str}`
* **Execution Mode**: `{run_mode}`
* **LLM Model**: `{selected_model}`
* **Input File**: `{uploaded_file.name}`
* **Loaded Knowledge Base**: `{', '.join(kb_files)}`
* **Compliance Frameworks**: HKFRS / IFRS / ISO 27001 (Data Minimization) / ISO 42001 (AIMS)
"""
                final_report = raw_report + audit_trail

                st.markdown("---")
                st.markdown(f"## {t['report_header']}")
                st.markdown(final_report)
                
                st.download_button(
                    label=t["btn_download"],
                    data=final_report,
                    file_name=f"FinBrief_Report_{lang_code}_{datetime.now().strftime('%Y%m%d')}.md",
                    mime="text/markdown"
                )

            except Exception as e:
                st.error(f"❌ AI Error: {str(e)}")
